rpn:
  name: rpn
  backbone: resnet101
  anchor_base_size: 256
  anchor_ratios: [0.5, 1, 2]
  anchor_scales: [0.125, 0.25, 0.5, 1, 2]
  base_conv_channels: 512
  input_channels: 1024
  score_thresh: 0.7
  nms_threshold: 0.7
  top_n: 2000
  pool_size: 7
  stride: 16

detector:
  name: detector
  num_classes: 20
  input_channels: 2048
  top_n: 19
  score_thresh: 0.7
  nms_threshold: 0.7

trainer:
  name: trainer
  experiment_name: "sample_train"
  image_base_size: 600
  stride: 16
  grad_clip: 10
  bg_low: 0
  bg_high: 0.3
  fg_low: 0.7
  pos_prop_perc: 0.5
  prop_batch: 256
  pool_size: 7
  margin: 100
  clobber_positive: False
  neg_iou_thresh: 0.3
  pos_iou_thresh: 0.7
  pos_anchors_perc: 0.5
  anchor_batch: 256
  epochs: 100
  backbone: resnet101
  detector_lr: 1e-4
  backbone_head_lr: 1e-4
  backbone_tail_lr: 1e-4
  rpn_lr: 1e-4
  train_type: 4step
  
image_base_size: 600
dataset: voc